### ISSUE TITLE
ValueError: Dimension 0 in both shapes must be equal,

### ISSUE THREAD

**Issue by Kacho1996** [testingautomated-usi/selforacle#6]
Hello selfOcracle
Can you please fix this issue.  

  raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 153600 and 38400. Shapes are [153600,512] and [38400,512]. for 'Assign_42' (op: 'Assign') with input shapes: [153600,512], [38400,512].

**Comment by Siyuluan** [comment]
Hi，

I faced the same bugs. Did you solved it?
